apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc4m
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bc4m
  template:
    metadata:
      labels:
        app: bc4m
    spec:
      containers:
      - name: api
        image: sametaydinq/bestcloudforme:latest
        ports:
        - containerPort: 2000
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3